theme: minima
title: Ruohai's Blog
description: Thoughts on CFD and AI
author:
  name: Ruohai
url: "https://ruohai0925.github.io"
show_excerpts: true

giscus:
  repo: ruohai0925/ruohai0925.github.io
  repo_id: R_kgDORSwM5A
  category: General
  category_id: DIC_kwDORSwM5M4C2rly
