theme: minima
title: Ruohai's Blog
description: Exploring the intersection of Computational Fluid Dynamics and AI
author:
  name: Ruohai
url: "https://ruohai0925.github.io"
show_excerpts: true

header_pages:
  - about.md

giscus:
  repo: ruohai0925/ruohai0925.github.io
  repo_id: R_kgDORSwM5A
  category: General
  category_id: DIC_kwDORSwM5M4C2rly
